### ISSUE TITLE
After connecting to Engine Server it doesn't response

### ISSUE THREAD

**Issue by dBurva20** [KuhakuPixel/AceTheGame#26]
As the title mentioned, I was able to connected to Engine server but what I wrote after doens't get any response.

Ps: I was using it for digimon digital tamers, because I messed up my save file and didn't want to grind again. Thanks to your patch method my save file turned back to a day before and that was I was trying to do. Thanks for it xd :D

**Comment by KuhakuPixel** [comment]
this discussion has been moved to discord, I suppose I can close it
