### ISSUE TITLE
Scanning an exact value (=) takes 20 minutes

### ISSUE THREAD

**Issue by t0rzz** [KuhakuPixel/AceTheGame#81]
As subject says, scanning a known integer value in a process takes about 20 minutes.

scan type: =
value type: int (32bit)
Region level: all_read_write

rooted.

**Comment by KuhakuPixel** [comment]
what game did u try it on? 

have you tried `region level` of `heap_stack_executable_bss` ? 

which should speed up the scan

**Comment by t0rzz** [comment]
> what game did u try it on?
> 
> have you tried `region level` of `heap_stack_executable_bss` ?
> 
> which should speed up the scan

heap_stack_executable_bss scan is much more faster.
Thank you
