### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by 0x00A1FA** [KuhakuPixel/AceTheGame#86]
Hello,

I think we can all agree that the icon needs to be something more symbolic and recognizable. Something like the GameGuardian logo.

I've made the following
![New logo](https://github.com/KuhakuPixel/AceTheGame/assets/110613761/f6e0a91d-2ad2-4281-adbe-e445b809418c).

Let me know if you want me to tweak it.

Thanks!

**Comment by KuhakuPixel** [comment]
Hello @0x00A1FA, sorry for the late reply

I am not interested in having a new logo for now, maybe in the future .....
