### ISSUE TITLE
Can this project help finding offset?

### ISSUE THREAD

**Issue by tuandev1l** [KuhakuPixel/AceTheGame#88]
As title, can this project help finding offset or something like "find out what wrote/accessed to this memory" feature like cheat engine ?

**Comment by KuhakuPixel** [comment]
currently no, I think `find out what wrote/accessed to this memory` would require something like a debugger to be integrated 

its in the roadmap to implement a debugger, but cant promise you when

**Comment by tuandev1l** [comment]
Yeb, i am looking forward to this. +1 star and watch this pj. Thank you for sharing.
